// ─────────────────────────────────────────────────────────────
//  DIFFICULTIES
// ─────────────────────────────────────────────────────────────
export const DIFFICULTIES = {
  beginner: {
    key: "beginner",
    title: "Beginner",
    description: "3 characters • 1 werewolf • 2 mistakes",
    characterCount: 3,
    gridCols: 3,
    werewolfCount: 1,
    corruptedCount: 0,
    maxMistakes: 2,
    allowedRoles: ["confessor", "witness", "neighbour"],
  },
  easy: {
    key: "easy",
    title: "Easy",
    description: "5 characters • 1 werewolf • 2 mistakes",
    characterCount: 5,
    gridCols: 3,
    werewolfCount: 1,
    corruptedCount: 0,
    maxMistakes: 2,
    allowedRoles: ["confessor", "witness", "neighbour", "watchman"],
  },
  normal: {
    key: "normal",
    title: "Normal",
    description: "6 characters • 1 werewolf • 1 corrupted • 2 mistakes",
    characterCount: 6,
    gridCols: 3,
    werewolfCount: 1,
    corruptedCount: 1,
    maxMistakes: 2,
    allowedRoles: [
      "confessor",
      "witness",
      "neighbour",
      "watchman",
      "doctor",
      "diviner",
    ],
  },
  hard: {
    key: "hard",
    title: "Hard",
    description: "7 characters • 2 werewolves • 1 corrupted • 2 mistake",
    characterCount: 7,
    gridCols: 3,
    werewolfCount: 2,
    corruptedCount: 1,
    maxMistakes: 2,
    allowedRoles: [
      "confessor",
      "witness",
      "neighbour",
      "watchman",
      "doctor",
      "diviner",
      "president",
      "recluse",
    ],
  },
  expert: {
    key: "expert",
    title: "Expert",
    description: "9 characters • 2 werewolves • 1 corrupted • 2 mistake",
    characterCount: 9,
    gridCols: 3,
    werewolfCount: 2,
    corruptedCount: 1,
    maxMistakes: 2,
    allowedRoles: [
      "confessor",
      "witness",
      "neighbour",
      "watchman",
      "doctor",
      "diviner",
      "president",
      "recluse",
      "silent",
    ],
  },
  insane: {
    key: "insane",
    title: "Insane",
    description: "12 characters • 3 werewolves • 2 corrupted • 2 mistakes",
    characterCount: 12,
    gridCols: 3,
    werewolfCount: 3,
    corruptedCount: 2,
    maxMistakes: 2,
    allowedRoles: [
      "confessor",
      "witness",
      "neighbour",
      "watchman",
      "doctor",
      "diviner",
      "president",
      "recluse",
      "silent",
    ],
  },
};

// progression order
export const DIFFICULTY_ORDER = [
  "beginner",
  "easy",
  "normal",
  "hard",
  "expert",
  "insane",
];

// ─────────────────────────────────────────────────────────────
//  PROFESSIONS
// ─────────────────────────────────────────────────────────────
export const PROFESSIONS = [
  "Blacksmith",
  "Baker",
  "Mayor",
  "Hunter",
  "Miller",
  "Gardener",
  "Fisherman",
  "Barman",
  "Carpenter",
  "Miner",
  "Tailor",
  "Herbalist",
  "Shepherd",
];
