export const appTheme = {
  colors: {
    background: "#202449",
    surface: "#2E3166",
    surfaceAlt: "#2B3166",
    panel: "#2A2E5A",
    primary: "#494C95",
    primaryAlt: "#3D40A0",
    borderStrong: "#050505",
    borderSoft: "#D5DAFF",
    borderMuted: "#6268AD",
    divider: "#373B72",
    textMain: "#E4E7FF",
    textSub: "#D8DCFF",
    textMuted: "#BFC5F6",
    textHint: "#9DA5E5",
    textButtonDark: "#000000",
    textButtonDarkSoft: "#121212",
    action: "#6B70BE",
    actionDisabled: "#565B9A",
    actionDisabledBorder: "#282D58",
    bubbleBackground: "#E4E7FF",
    bubbleText: "#0C1028",
    cardPlaceholderBorder: "#38407E",
    cardPlaceholderBackground: "#252B57",
  },
  radius: {
    sm: 12,
    md: 16,
    lg: 20,
    xl: 22,
    xxl: 24,
  },
  borderWidth: {
    sm: 2,
    md: 3,
    lg: 4,
    xl: 6,
  },
};

export const sharedStyleObjects = {
  safeArea: {
    flex: 1,
    backgroundColor: appTheme.colors.background,
  },
  primaryButton: {
    width: "100%",
    borderRadius: appTheme.radius.xl,
    borderWidth: appTheme.borderWidth.xl,
    borderColor: appTheme.colors.borderStrong,
    backgroundColor: appTheme.colors.primary,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  primaryButtonText: {
    color: appTheme.colors.textButtonDark,
    fontWeight: "600",
    textAlign: "center",
  },
  secondaryButton: {
    width: "100%",
    borderRadius: appTheme.radius.lg,
    borderWidth: appTheme.borderWidth.lg,
    borderColor: appTheme.colors.borderSoft,
    backgroundColor: appTheme.colors.panel,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  secondaryButtonText: {
    color: appTheme.colors.textMain,
    fontSize: 19,
    fontWeight: "600",
    textAlign: "center",
  },
};
